name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main # ✅ Triggers only when pushing to `main`
  workflow_dispatch: # ✅ Allows manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Trigger Streamlit Cloud Redeployment
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.STREAMLIT_DEPLOY_TOKEN }}" \
          https://api.streamlit.io/v1/deploy
